#!/bin/bash

# Use Directly from Docker hub if not provided:
IMG_NAME="${IMG_NAME:-nishanthmenon/ccs-msp430-ci}"

D=`echo "$(cd "$(dirname "$0")"; pwd -P)/"`
docker run -it --rm						\
	       -v $D/workdir:/workdir				\
	       -v $D/workspace:/workspace			\
	       -v $D:/automation_iface				\
	       ${IMG_NAME}					\
	       /usr/bin/make $*
